project:
  output-dir: _build/print/6x9/typst

trim-width: 6in
trim-height: 9in

format:
  typst:
    toc: true
    number-sections: true
    keep-typ: true
    template-partials:
      - typst/typst-show.typ
    margin:
      top: 0.65in
      bottom: 0.75in
    margin-geometry:
      inner:
        far: 0.80in
        width: 0in
        separation: 0in
      outer:
        far: 0.65in
        width: 0in
        separation: 0in
      clearance: 8pt
