project:
  output-dir: _build/print/7x10/latex

format:
  pdf:
    documentclass: scrbook
    classoption:
      - twoside
      - openright
    pdf-engine: lualatex
    keep-tex: true
    include-in-header: latex/book-layout.tex
    template-partials:
      - latex/title.tex
      - latex/before-body.tex
    geometry:
      - paperwidth=7in
      - paperheight=10in
      - inner=0.85in
      - outer=0.70in
      - top=0.70in
      - bottom=0.80in
